version: "3.3"
services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: mysql-tech-talk
        environment:
          - MYSQL_ROOT_PASSWORD=nimda
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=admin
          - MYSQL_DATABASE=jenkins-multi-branch-pipeline
        ports:
          - "3306:3306"
        volumes:
          - ./data/mysql:/var/lib/mysql
    jenkins:
        image: jenkins/jenkins:lts
        restart: always
        links:
            - mysql
        container_name: jenkins-tech-talk
        volumes:
            - ./data/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - JENKINS_HOST_HOME:./data/jenkins-home/
            - JENKINS_PASSWORD:nimda
        ports:
            - "8080:8080"
            - "5000:5000"
            - "50000:50000"
    nginx:
        image: nginx:latest
        container_name: nginx-tech-talk
        volumes:
            - ./data/nginx/sites-enabled/:/etc/nginx/conf.d/
        restart: always
        ports:
            - "80:80"
            - "443:443"
        links:
            - jenkins